name: example
description: Demonstrates how to use the fl_rangers_applog plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  fl_rangers_applog:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
