name: fl_rangers_applog
description: flutter plugin for RangersAppLog, only Android and IOS are supported
version: 0.1.1
repository: https://github.com/Wayaer/fl_rangers_applog.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.fl.rangers.app.log
        pluginClass: FlRangersAppLogPlugin
      ios:
        pluginClass: FlRangersAppLogPlugin
